### ISSUE TITLE
Negative numbers are not supported

### ISSUE THREAD

**Issue by tbayart** [Tyrrrz/QuickJson#1]
### Version

1.0.0

### Details

Reading the following json fails : 
`{ "Delta":-25 }`
removing the hyphen allows to read it successfully

### Steps to reproduce

Create a simple console application 
Add the following lines :
```
var json = Json.TryParse("{ \"Delta\":-25 }");
Console.WriteLine($"json=[{json}]");
json = Json.Parse("{ \"Delta\":-25 }");
Console.WriteLine($"json=[{json}]");
```
First line will return null, so output will be
`json=[]`
Third line will generate an exception
`System.InvalidOperationException: Failed to parse JSON. Unexpected character sequence at position 10: '-25 }'.`

**Comment by Tyrrrz** [comment]
Thanks for the report!

**Comment by tbayart** [comment]
Thanks for the quick fix
