### ISSUE TITLE
Number in exponential notation fails to decode

### ISSUE THREAD

**Issue by tbayart** [Tyrrrz/QuickJson#2]
### Version

1.0.1

### Details

Reading the following json fails :
`{ "Delta":5.4339e+08 }`

### Steps to reproduce

Create a simple console application
Add the following lines :
```
var json = Json.Parse("{ \"Delta\":2.5e+11 }");
Console.WriteLine($"json=[{json}]");
```
Execution of the code will generate an exception
`System.InvalidOperationException: Failed to parse JSON. Unexpected character sequence at position 13: 'e+11 }'.`

Since numbers can have many representations, the following official site could be a useful source of decoding patterns :
https://www.json.org/

**Comment by Tyrrrz** [comment]
Thanks! Fixed this too

**Comment by tbayart** [comment]
Good job, i successfully parsed my 704255 lines length json file (295 852 867 bytes) 👍

**Comment by Tyrrrz** [comment]
> Good job, i successfully parsed my 704255 lines length json file (295 852 867 bytes) 👍

Awesome!
